sudo: required

services:
  - docker

env:
  global:
    DOCKER_USERNAME:
      secure: "gfcELyterYFafX2FCvvKh0s/B+oOupZX79lNmASYkVWj0F6gAvbnE/jfs8hBr0mx7wg/SdtALn/ypLd5LGfUiR34xWDcVRKksn0Ospi/AhcTyWx+2ikmx0j8/5K41ejB2NcI5qHqS9s+SHLd48v0Ozain7FpY1iaoutbMOOCDDfpwmtjjc2Zh/S9gVoa+Yvjr8pbuTa9eZCgNzn74DIfVTM2kDcch0WoEgIEK9KeEuPMdPvo0+yl/PPudPeE74Er5eQbZJQKTdZh/ainFAz8NOVW5vM2gQocblLKVKvAza28wtuMEyPhWKkUh+jVUMAVs1ZGb5I9hlAzFo7aVWmtJw7XUEMZPKX6PshygkP+dwbQz5vxtRs2ZPhEWm8DcJvzAFSake7dWFv3QW8qJqjh0m5CM005yDxNgL6bd8LcNSOyRIfu8t4r6RY1qaTLdYugCSFDB6yBGTximZz24VbpD9xF30sE+hu8YDuyqKXqGSyt0bmWF/2/fg0OAotshTtY3XAyemcZE/UKPr9d8UXu5NaedDmbESA7oTXlhpBZWbbJQcgO4Sykh3+x9hCGp9vvJNbggv73NElYY4+alzmECXVjLa5cyWwMgJoGQpyvY8TD4zGA8ejcJ46lNxUVakomgNHRPn1+vgDMtPBnHGNeBQMgIT3e05wKDdaVLhqlic8="
    DOCKER_PASSWORD:
      secure: lZrSWmlprkhF7eBG3HXyJe1865Oq0IhEKKf0nxpcog3wvVrjKO3pu+vfuCUPCqebEjdW2pvLxkIpvb1vWL0FRSwVLafmPFC27ghZzjRNX7UPNAyvSxY98czTuBgjjFVsGQVCqnPxUtHYGyEHMsy+mAREzChiGwT+ThNc821R6qVoxUSVKe7hV5gy/LALWP9P9opiEIKl1bAQouAHViA7LRjhwmYFt69Kr2F3ZEvyMD3O2DSxmLm3Gb5ceDOzcwG6XWhRj9AJetJyBFP3ju/dFnJSu91NU4ytI+FfME9mYJle85EZHZA1WNHlWko7WbMXe/CsWiaVkUjkXLHyG878RRv8Xi5fK/ITq2Ap7XUVtOggYniSsv7NdlAFypK2sk4Vhgiv2kk72IPH3pMZhgs6USuxkGQ+QE1JSRHW7pNQLZwoGTDUtZBZhZmIy3kOABfcOq16uQcrL009KnWODfzFKofYDzvy7dmd56miKTZdVDbGMOSyU0SdOtP6qMSOWumRHOI4j95YRKdvV1VqKTnJFKul3W67D5FKybyqbU0vkP7ArjG+7ralmH4xfiT8OBTvw6VFsvwStzeiTBPbikEbWsVO+xzgo6shgdODnmwhzMWiJi7OYQQ9m3FU+5NtovVfInNqkzHT0cZwO9wvNCqpkygUSk/fDnQ/VcAtwXOdQaA=

before_script:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker build -t image .
  - docker tag image jleeothon/docker-eslint:latest
  - docker push jleeothon/docker-eslint:latest

script: []
